<a href="https://colab.research.google.com/github/mosabbeer/Machine_Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#starting chapter 1
import numpy as np
temprature = np.array([33.5,22,44.5,50.5])
average = np.mean(temprature) #average
print(average)
print(temprature)
print(np.zeros(4)) #all the value zero 1d
print(np.zeros((4,5))) #all the value zero 2d
print(np.ones((2,3))) #value of one
print(np.full((2,2),6)) #2d array of 6
print(np.full(3,3)) #meke one d array using it
print(np.arange(1,10,1)) #as like as forloop, start,end-1,increment/decrement
print(np.eye(3))#identity matrix


37.625
[33.5 22.  44.5 50.5]
[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6]
 [6 6]]
[3 3 3]
[1 2 3 4 5 6 7 8 9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#chapter_2
array = np.array([[1,2,3],[5,6,7],[8,9,10],[9,11,3]])
print(array.shape) #(row,column)
print(array.size) #number of element
print(array.ndim) #number of dimantion
print(array.dtype)#type of element checking
arr=np.array([10.2,20.5,30.99])
int_arr=arr.astype(int) #changing datatype
print(int_arr)
#arithmetic operator worked with all the values without loop
print(int_arr+10)
print(int_arr-10)
print(int_arr*10)
print(int_arr/10)
print(int_arr/10)
arr_agri=np.array([10,20,30,40,50])
print(np.mean(arr_agri)) #average
print(np.sum(arr_agri))#sumation
print(np.min(arr_agri))#min
print(np.max(arr_agri))#max
print(np.std(arr_agri))#standard daviation
print(np.var(arr_agri)) #varaition


(4, 3)
12
2
int64
[10 20 30]
[20 30 40]
[ 0 10 20]
[100 200 300]
[1. 2. 3.]
[1. 2. 3.]
30.0
150
10
50
14.142135623730951
200.0


In [ ]:
#chapter_3 indexing and slicing
#indexing means choose an element
#slicing means choosing a part of the array
"""
array[index]= 1D
array[row,column]=2D
"""
int_arr=np.array([10,20,30,40,50,60,70,80])
print(int_arr)
print(int_arr[3]) #indexing
#slicing->starting,stop-1,step
print(int_arr[0:3])
print(int_arr[0:3:2])
print(int_arr[::-1]) #in reverse order
#fency indexing =selecting multiple elment at once
print(int_arr[[1,3,2]]) #selecting 2nd 4th 3rd element
#bolian masking = based on condition
print(int_arr[int_arr>25])
#reshaping array 1D=2D,1D=3D without changing values arr.reshape(row,column)
print(int_arr.reshape(2,4))
"""
multidimentional to 1D
revel--> change the main array
flatten()--> create a copy
"""
arr_2d=np.array([[1,2,3],[3,4,5],[3,5,6]])
print(arr_2d.flatten())
print(arr_2d.ravel())




[10 20 30 40 50 60 70 80]
40
[10 20 30]
[10 30]
[80 70 60 50 40 30 20 10]
[20 40 30]
[30 40 50 60 70 80]
[[10 20 30 40]
 [50 60 70 80]]
[1 2 3 3 4 5 3 5 6]
[1 2 3 3 4 5 3 5 6]


In [ ]:
"""
np.insert(array,index,value,asix=None)
inserting
"""
array=np.array([10,20,30,40])
new_array=np.insert(array,2,100,0)
new_array
arr_2d=np.array([[1,2,3],[2,3,5]])
new_2d=np.insert(arr_2d,1,[5,6],axis=1) #5,6 means raw value, axis=0, 0th exis,axis=1(column wise),1 means 2nd row
print(new_2d)
#append -->at the end
"""
same as insert
"""
arr=np.array([1,2,3])
new_arr=np.append(arr,[4,5,6])
print(new_arr)
np.concatenate([arr,new_arr],axis=0) #axis=1 column wise
print(arr)
np.delete(new_arr,0,axis=None)
new_2d=np.delete(arr_2d,0,axis=0)
print(new_2d)
"""
vstake() row wise
hstake() column wise
"""
new_arr=np.array([1,6,3])
np.hstack((arr,new_arr))
np.vstack((arr,new_arr))
np.split(new_arr,3)


[[1 5 2 3]
 [2 6 3 5]]
[1 2 3 4 5 6]
[1 2 3]
[[2 3 5]]


[array([1]), array([6]), array([3])]

In [ ]:
# brodcasting--> without using array doing some mathmetical task
prices=[100,200,300]
prices=np.array(prices)
discount=10
final_prices=prices-(prices*discount/100)
print(final_prices)

[ 90. 180. 270.]


In [ ]:
#hendling missing value
"""
np.isnan->ditect mmissing value
np.NAN_to_num()->replacing with any value
np.isinf()->detect infinite number
"""
arr=np.array([1,2,np.nan,3,np.nan,6])
print(np.isnan(arr)) #true = nan,
new_arr=np.nan_to_num(arr,nan=9)
print(new_arr)

[False False  True False  True False]
[1. 2. 9. 3. 9. 6.]
